import { Lead, CalendarEvent } from "./types";

export const seedLeads: Lead[] = [
  {
    id: "lead-1",
    name: "María García",
    phone: "+525511223344",
    email: "maria.garcia@email.com",
    furnitureType: "Mesa de comedor de madera de encino",
    estimatedValue: 15000,
    notes: "Quiere una mesa para 8 personas con acabado natural.",
    stage: "nuevo_lead",
    lastContact: "2026-04-10",
    createdAt: "2026-04-10",
  },
  {
    id: "lead-2",
    name: "Carlos López",
    phone: "+525522334455",
    email: "carlos.lopez@email.com",
    furnitureType: "Sala modular de 3 piezas",
    estimatedValue: 28000,
    notes: "Vive en departamento pequeño, necesita diseño compacto.",
    stage: "contactado",
    lastContact: "2026-04-11",
    createdAt: "2026-04-08",
  },
  {
    id: "lead-3",
    name: "Ana Martínez",
    phone: "+525533445566",
    email: "ana.martinez@email.com",
    furnitureType: "Closet empotrado para recámara principal",
    estimatedValue: 22000,
    notes: "Medidas: 3m x 2.5m. Quiere iluminación interior LED.",
    stage: "cotizacion_enviada",
    lastContact: "2026-04-12",
    createdAt: "2026-04-05",
  },
  {
    id: "lead-4",
    name: "Roberto Sánchez",
    phone: "+525544556677",
    email: "roberto.sanchez@email.com",
    furnitureType: "Escritorio ejecutivo con repisas",
    estimatedValue: 12000,
    notes: "Home office. Necesita gavetas con cerradura.",
    stage: "negociacion",
    lastContact: "2026-04-13",
    createdAt: "2026-04-01",
  },
  {
    id: "lead-5",
    name: "Laura Hernández",
    phone: "+525555667788",
    email: "laura.hernandez@email.com",
    furnitureType: "Juego de comedor completo (mesa + 6 sillas)",
    estimatedValue: 35000,
    notes: "Prefiere tapicería en tonos neutros. Sillas con cojín.",
    stage: "venta_cerrada",
    lastContact: "2026-04-09",
    createdAt: "2026-03-25",
  },
  {
    id: "lead-6",
    name: "Fernando Torres",
    phone: "+525566778899",
    email: "fernando.torres@email.com",
    furnitureType: "Rack para TV de 65 pulgadas",
    estimatedValue: 8500,
    notes: "No definieron presupuesto. Contestó frío al follow-up.",
    stage: "venta_perdida",
    lastContact: "2026-04-02",
    createdAt: "2026-03-20",
  },
  {
    id: "lead-7",
    name: "Patricia Ruiz",
    phone: "+525577889900",
    email: "patricia.ruiz@email.com",
    furnitureType: "Cama king size con cabecera tapizada",
    estimatedValue: 18000,
    notes: "Diseño minimalista. Color gris claro.",
    stage: "contactado",
    lastContact: "2026-04-12",
    createdAt: "2026-04-09",
  },
  {
    id: "lead-8",
    name: "Jorge Castillo",
    phone: "+525588990011",
    email: "jorge.castillo@email.com",
    furnitureType: "Isla de cocina con encimera de cuarzo",
    estimatedValue: 42000,
    notes: "Proyecto de remodelación completa de cocina.",
    stage: "cotizacion_enviada",
    lastContact: "2026-04-13",
    createdAt: "2026-04-03",
  },
  {
    id: "lead-9",
    name: "Sofía Morales",
    phone: "+525599001122",
    email: "sofia.morales@email.com",
    furnitureType: "Librero empotrado de piso a techo",
    estimatedValue: 16000,
    notes: "Para sala de estar. Quiere combinación de entrepaños abiertos y cerrados.",
    stage: "nuevo_lead",
    lastContact: "2026-04-13",
    createdAt: "2026-04-13",
  },
  {
    id: "lead-10",
    name: "Diego Vargas",
    phone: "+525500112233",
    email: "diego.vargas@email.com",
    furnitureType: "Barra con 4 taburetes para terraza",
    estimatedValue: 11000,
    notes: "Materiales resistentes a intemperie. Acabado rústico.",
    stage: "negociacion",
    lastContact: "2026-04-11",
    createdAt: "2026-04-06",
  },
];

export const seedEvents: CalendarEvent[] = [
  {
    id: "event-1",
    title: "Llamada con María García",
    date: "2026-04-14",
    time: "10:00",
    type: "llamada",
    clientId: "lead-1",
    clientName: "María García",
    notes: "Confirmar medidas de la mesa y enviar catálogo de acabados.",
  },
  {
    id: "event-2",
    title: "Entrega - Sala Modular Carlos López",
    date: "2026-04-16",
    time: "14:00",
    type: "entrega",
    clientId: "lead-2",
    clientName: "Carlos López",
    notes: "Entregar al departamento en Col. Del Valle. Llevar 2 ayudantes.",
  },
  {
    id: "event-3",
    title: "Follow-up - Cotización Ana Martínez",
    date: "2026-04-15",
    time: "11:30",
    type: "follow_up",
    clientId: "lead-3",
    clientName: "Ana Martínez",
    notes: "Preguntar si revisó la cotización del closet.",
  },
  {
    id: "event-4",
    title: "Llamada - Cierre Roberto Sánchez",
    date: "2026-04-15",
    time: "16:00",
    type: "llamada",
    clientId: "lead-4",
    clientName: "Roberto Sánchez",
    notes: "Negociar precio final del escritorio. Tiene otra cotización.",
  },
  {
    id: "event-5",
    title: "Entrega - Juego Comedor Laura Hernández",
    date: "2026-04-18",
    time: "09:00",
    type: "entrega",
    clientId: "lead-5",
    clientName: "Laura Hernández",
    notes: "Entrega final. Verificar sillas antes de salir.",
  },
  {
    id: "event-6",
    title: "Medición en sitio - Jorge Castillo",
    date: "2026-04-17",
    time: "10:00",
    type: "otro",
    clientId: "lead-8",
    clientName: "Jorge Castillo",
    notes: "Ir a tomar medidas exactas de la cocina para la isla.",
  },
];
